### ISSUE TITLE
error trying to install maxmertkit from bower  ENOTFOUND     Package . not found

### ISSUE THREAD

**Issue by tvmaly** [maxmert/maxmertkit#79]
I was attempting to install maxmertkit with 

bower install maxmertkit -V .

I get an error message 

bower cached        git://github.com/maxmert/maxmertkit.git#1.0.5
bower validate      1.0.5 against git://github.com/maxmert/maxmertkit.git#*
bower ENOTFOUND     Package . not found

Stack trace:
Error: Package . not found
    at createError (/usr/local/lib/node_modules/bower/lib/util/createError.js:4:15)
    at /usr/local/lib/node_modules/bower/lib/core/resolverFactory.js:143:27
From previous event:
    at PackageRepository.fetch (/usr/local/lib/node_modules/bower/lib/core/PackageRepository.js:45:6)
    at Manager._fetch (/usr/local/lib/node_modules/bower/lib/core/Manager.js:299:51)
    at Array.forEach (native)
    at Manager.resolve (/usr/local/lib/node_modules/bower/lib/core/Manager.js:102:23)
    at Project._bootstrap (/usr/local/lib/node_modules/bower/lib/core/Project.js:542:6)
    at /usr/local/lib/node_modules/bower/lib/core/Project.js:79:21

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.12.0
OS: Linux 3.13.0-46-generic ia32

**Comment by tvmaly** [comment]
Documentation had an extra period, I just realized this was the problem.  Please close this issue.
