### ISSUE TITLE
running gulp  kitSass fails with TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by tvmaly** [maxmert/maxmertkit#80]
[10:00:14] Using gulpfile ~/webdev/test/gulpfile.js
[10:00:14] Starting 'kitJson'...
[10:00:14] Starting 'kitCoffee'...
[10:00:14] Starting 'kitSass'...
[10:00:15] 'kitSass' errored after 7.96 ms
[10:00:15] TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:471:13)
  at module.exports (/home/tmaly/webdev/test/node_modules/gulp-ruby-sass/index.js:65:15)
  at Gulp.<anonymous> (/home/tmaly/webdev/test/gulpfile.coffee:113:10)
  at module.exports (/home/tmaly/webdev/test/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/home/tmaly/webdev/test/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/tmaly/webdev/test/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/home/tmaly/webdev/test/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
  at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3

[10:00:17] Finished 'kitJson' after 2.9 s
[10:00:24] gulp-size: maxmertkit.js 91.33 kB
[10:00:24] Finished 'kitCoffee' after 11 s

**Comment by tvmaly** [comment]
this is related to a breaking change in the latest gulp-ruby-sass
http://stackoverflow.com/questions/28140012/gulp-typeerror-arguments-to-path-join-must-be-strings
the simplest work around is probably to use gulp-sass   I am still working on a solution

**Comment by tvmaly** [comment]
Ok here is what worked for me
first run:  npm install gulp-sourcemaps
and npm install gulp-sass



then edit your gulpfile.coffee

change the gulp-ruby-sass  import to 
sass = require 'gulp-sass'
and add line 
sourcemaps = require 'gulp-sourcemaps'

then edit the two tasks that use sass
to:

gulp.task 'kitSass', ->

	files = [
		"#{path.kit.sass}/main.sass"
	]

	gulp.src( files )
	    .pipe( plumber() )
	    # .pipe( cache('kitSass') )
            .pipe(sourcemaps.init())
            .pipe(sass({
                errLogToConsole: true
            }))
            .pipe(sourcemaps.write())
	    .pipe( size( showFiles: yes ) )
	    .pipe( gulp.dest "#{path.kit.css}" )
	    # .pipe( livereload() )

gulp.task 'docsSass', ->

	files = [
		"#{path.docs.front.sass}/developer.sass"
	]

	gulp.src( files )
	    .pipe( plumber() )
	    # .pipe( cache('kitSass') )
            .pipe(sourcemaps.init())
            .pipe(sass({
                errLogToConsole: true
            }))
            .pipe(sourcemaps.write())
	    .pipe( size( showFiles: yes ) )
	    .pipe( gulp.dest "#{path.docs.front.css}" )
	    # .pipe( livereload() )


then you can run your gulp command
